
<main role="main">
	<div class="terms jumbotron jumbotron-fluid mb-0">
	  <div class="container">
		  <h1 class="headline">TERMS OF USE</h1>
		  <div class="lead">Please read these terms of use carefully before using Our Service.</div>
		  <ul>
		  	<li>Last Updated as of September 24, 2021</li>
		  </ul>
	  </div>
	</div>
	<div class="simple-content tos">
	  <div class="container">
			<div class="row">
			  <div class="col-md-12">

<p>Cortiam Inc., also known as <a href="www.cortiam.com" target="_blank">www.cortiam.com</a> (hereafter referred to as "We", "Us", "Our", "Cortiam" or "Website") is creating a membership for real estate agents that truly benefits its users as it matches buyers and sellers with agents.</p>
<p>Persons or businesses that decide to fully access all the features available on Our Website may be required to register as a "User" depending on the level of service and access they want from Our Website. The term User also refers to "You" or "Your" whether or not registered with Our Website as a seller, real estate agent, or third party service provider.  Users using Our Website agree to these Terms of Use, the Disclaimer, as well as Our Privacy Policy whether or not they use Our Website or Services to look for information, real estate agents in their area, or advice. By visiting Our Website, You agree and accept these Terms of Use and the Privacy Policy all of which form a binding agreement ("Agreement") between You and Us.   If You do not agree to be bound by these Terms of Service or Our Privacy Policy, Your only recourse shall be to discontinue using or visiting Our Website. Each User acknowledges that this is a binding Agreement, and it governs use of the information found on Our Website or the "Services" (as that term is defined below) We make available through Our Website or other third parties and takes the place of any emails, texts or conversations between You and Us.</p>
<p>PLEASE READ THESE TERMS OF USE CAREFULLY. Use of the Website and any information or Services made available through the Website is limited to those individuals and entities who can form legally binding contracts under applicable law, and without limiting the foregoing, any information or Services made available through the Website is not to be accessed or used by minors.</p>
<p>Before using any of the "Information" or "Services" (as those terms are defined below) made available on or through Our Website, Users acknowledge and agree that they have read and agree to be bound by this Agreement in its entirety. Users agree to be bound by any changes to this Agreement and check back from time to time.  We may revise or amend the Terms of Use at any time without prior notice and Users agree the revisions or amendments will be effective upon updating on this Website with those changes or amendments. We agree to change the "Last Updated" date appearing at the top of this page to reflect each time We make any changes to this Agreement. Continued use of the Website and/or Services following the posting of changes shall mean that You accept those changes as of the latest update, after we send you notice of the changes. Even if You agree to Our Terms of Use, We may deny You access to Our Website and/or the use of some or all of Our Information and Services in Our sole and absolute discretion, for any reason or no reason.</p>

<h5 class="mb-0 mt-4">DISCLAIMER</h5>
<p>By using Our Website, You agree to the terms of this Advertiser Disclosure and Disclaimer, as well as all of Our Terms of Use  and Privacy Policy. The Information contained in this Website is for general information and educational purposes only and may be sourced directly by Us or through third party sources believed to be reliable, but We can give no assurance of reliability, accuracy, timeliness or truthfulness. You agree to conduct your own due diligence and research and to accept all risks related to reliance on any news, Content, Information, or Services We provide or make available on Our Website. We make no representations, warranties, or guarantees of any kind, express or implied, about the completeness, accuracy, reliability, suitability of the Information made available through this Website and You agree to hold Us harmless from any claims or loss You may suffer as a result of Your use of the Information or Services made available through this Website. You agree that any reliance You place on the Information or Services made available by US on or through this Website is solely at Your own risk and You hereby agree to hold Us harmless and indemnify Us from any such loss or claims resulting from Your use of the Information or Services made available by Us or others on or through Our Website.</p>

<p>We may have financial interests in, or relationships with, some of the entities, businesses, and/or publications discussed or otherwise referenced on Our Website. Certain links that may be provided on Our Website are provided for convenience and do not imply Our endorsement, or approval of any real estate agents or third-party websites or their content. We are not authorized, registered or licensed in any capacity with any state or regional real estate licensing authority or the regulatory bodies or agencies of any country, state, province, or territory.</p>

<p><b>Although we check the current licensing status of the real estate agents that appear on Our Website, We have not conducted other due diligence or background checks on them.  By using Our Website, You agree to hold Us harmless from any loss caused by Your purchase, sale, or hiring of any User registered or a person or business advertising on Our Website. Do not rely on the Information provided or the Services made available on Our Website. Conduct Your own due diligence before engaging a person or business registered or advertising on Our Website.</b></p>

<p>In no event will We be liable for any loss or damage to You or any third parties including without limitation, indirect or consequential loss or damage, even if We are made aware of it or notified of it by You, or any loss or damage whatsoever arising from loss of data, money, assets, or profits arising out of, or in connection with, the use of Our Website. Our Website and Services may not always be available or properly functioning and You agree to hold Us harmless from any loss of data, money, assets, or profits arising out of, or in connection with, the inability to use or access Our Website or Services.</p>

<p>In no event will We be liable for any loss or damage to You or any third parties including, but not limited to, any loss caused in whole or in part by any inaccuracies or incompleteness, delays, interruptions, errors or omissions, including, but not limited to, those arising from Our negligence or the negligence of any of Our registered Users, service providers or sites we link to or contingencies beyond Our or any of Our service providers' control in procuring, compiling, interpreting, computing, reporting, or delivering the Information or Services.</p>

<p>We are not giving business advice, investment advice, tax advice, legal advice, or other professional advice by allowing You to use Our Website and Services. We are not making any recommendations or endorsements that You hire a particular real estate agent or sign a particular seller of real estate. Before engaging in an agreement regarding the buying or selling or real estate You should always do your own due diligence and consult a qualified professional.</p>

<p>The Information and Services We provide are provided to You on a strictly "as is," "where is," and "where available" basis. Neither We nor any of Our Users, service providers, or advertisers represent or warrant the accuracy, completeness, current status, non-infringement, merchantability, or fitness for a particular purpose of the Information contained on Our Website or the Services made available to You. We do not make any representations or warranties that access to Our Website or use of the Information or Services will be continuous, uninterrupted, or error-free.</p>

<p>Through this Website You are able to link to other sites which are not under Our control. We have no control over the nature, content, and availability of those third party sites. The inclusion of any links to those third party sites does not imply that We recommend or endorse the services they provide, or the views expressed by them.</p>

<p>Additionally, We may receive advertising, marketing, or promotional fees (which may be in the form of cash, or any other type of asset) from other companies or those wanting to promote their products or services, so We have a conflict of interest and/or interest in the Information We provide or the Services We make available on Our Website and that information and/or Content may be biased as a result.</p>

<h5 class="mb-0 mt-4">ADVERTISER DISCLOSURE - AFFILIATE AND REFERRAL PROGRAMS</h5>

<p>From time to time, We may enter into various affiliate and referral programs with others for which We receive compensation, so We have a conflict of interest and/or interest in the Information We provide or the Services We make available on Our Website and that Information and/or those Services may be biased as a result.</p>

<h5 class="mb-0 mt-4">BILLING/REFUNDS</h5>
<ul>
<li>Monthly membership fees are pre-billed and start at $59.99/month. Once you pay the membership fee, you will have access to Cortiam's services for 30 days. Customers can cancel service at any time*. If you decide to cancel your Cortiam Service, your subscription will remain active until the next billing cycle.</li>
<li>You have seven days after the start date of the current billing cycle to request a refund on that month's membership fee. All services will end after we have processed your refund request. Membership Fees are not eligible for refunds if any of the following scenarios are true:
	<ul>
	<li>You have purchased a Qualified Lead. Your membership fees will not be eligible for a refund.
	<li>Refund request comes after the seven day return period.
	<li>You have pending introductions.
	<li>Violating Cortiam's Terms of use could lead to the cancellation of membership services without a refund. Cortiam reserves the right to refuse refunds if there is any abuse to our refund policy or terms and conditions.
	</ul>
</li>
<li>The billing cycle will begin the day after the free trial period is over.</li>
<li>Monthly membership fees will be billed to the preferred payment method on file after the free trial period expires.</li>
<li>Services will be temporarily suspended when the trial period ends if there is no payment method on file.</li>
<li>You will continue to have access to all membership services up until the next billing cycle.</li>
<li>Leads start as low as $99. When a customer selects you as their real estate agent, you will have 72 hours to pay for the lead.
	<ul>
	<li>After 72 hours, We will return Qualified Leads to the Available Listings Pool.</li>
	<li>If a property owner changes their mind after you have paid for the lead, you will have five business days to send us a system message requesting a refund. We will review all requests for refunds within 48 hours. Cortiam reserves the right to refuse any refund that violates our refund policy.</li>
	<li>Leads will automatically be charged to the payment method on your account. We recommend updating your payment method before purchasing a lead if you want to use a different form of payment.</li>
	<li>Excessive patterns of winning leads and failing to complete the purchase within 72 hours will result in the cancellation of membership services.</li>
	</ul>
</li>
</ul>
<h5 class="mb-0 mt-4">CORTIAM POLICIES</h5>
<ul>
<li>Violating Cortiam Policies will result in the cancellation of membership services without a refund.</li>
<li>It is a violation of Cortiam's Privacy Policy to request, exchange, or provide contact information of any kind before purchasing a qualified lead through Cortiam. Violation of this policy will result in the cancelation of membership services.</li>
<li>Cortiam's 30-day free trial is only for first-time members of Cortiam. Agents can add their licenses to see leads in other states and should not purchase multiple memberships.</li>
<li>We designed Cortiam to be safe and secure for all users. Privacy is the cornerstone of our values. Attempting to contact a customer outside of Cortiam's platform will result in the cancellation of membership services and may result in a lifetime ban.</li>
</ul>
<h5 class="mb-0 mt-4">CORTIAM UPLOADS - FOR SELLERS AND AGENTS</h5>
<ul>
<li>Any Video, Image, Link, profile picture that is harassing, derogatory, contains inflammatory language or violates Cortiam's ethical policies will be removed and may result in the cancellation of Cortiam membership services.</li>
<li>Videos should be 90 seconds or less and uploaded to YouTube. Cortiam reserves the right to remove or cancel your membership services if any post or video violates the above criteria.</li>
<li>Home sellers should avoid capturing their addresses in pictures uploaded to our website.</li>
</ul>
<h5 class="mb-0 mt-4">WINS/INTRODUCTIONS</h5>
<ul>
<li>Monthly membership includes ten introductions and two wins each month
	<ul>
	<li>Introductions
		<ul>
		<li>Agents can have up to 10 introductions out at once.</li>
		<li>When a seller accepts or declines your introduction, that introduction is returned to you.</li>
		<li>Introductions do not expire and can be retracted at any time.</li>
		<li>At this time, agents can not purchase additional Introductions.</li>
		</ul>
	</li>
	<li>Wins
		<ul>
		<li>Agents can win up to 2 listings each month.</li>
		<li>A win will subtract once the Agent completes payment for a Qualified Lead.</li>
		<li>Once an agent has won 2 properties in a billing period, the Agent will not win additional properties.</li>
		<li>At this time, Agents cannot purchase additional wins.</li>
		<li>See Refund Policy above for more information*</li>
		</ul>
	</li>
</ul>
<h5 class="mb-0 mt-4">DEFINITIONS</h5>
<b>Registration As A User</b><br>
<p>When You register, You may be required to register by creating an account and then signing into Our Website. If You register, You represent and warrant to Us that: (i) You are of legal age to form a binding contract, and, if You are acting on behalf of an organization, You have the right to enter this Agreement on behalf of such organization; (ii) You will provide Us with accurate, current and complete registration information; (iii) Your registration and Your use of the Website and Services is not prohibited by law; and (iv) You have all legal rights to provide the Content You post on this Website and will not violate any confidentiality agreements, copyright or trademark laws, intellectual property agreements, court orders, or other laws or agreements that may prohibit You from posting such information, posts, comments or other such Content on Our Website. We reserve the right to terminate or suspend Your status as a User in the event that You breach any term of this Agreement.</p>
<ol>
<li>About the Cortiam Website.
	<ol style="list-style-type: lower-alpha;">
	<li>The Cortiam Website is presented as a real estate agent lead generation platform and directory providing a system for communication between persons and entities wishing to sell real estate as a seller or provide selling services as an agent. Our Website provides access to Our virtual community of Users. Cortiam does not vouch for any of its Users. Cortiam does not endorse any of its Users and does not sanction statements that Users make on the platform or elsewhere on Our Website, although from time to time We may review what Users post.</li>
	<li>Cortiam does not offer any legal advice or financial advice and We are not involved in agreements between Users or in any legal or other selling type of representation of Users. From time to time, We may have several plans to choose from and the Services You will receive are based on the plan You sign up for. Users agree and represent that Cortiam shall at no point be held liable for the actions or omissions of any User. Users agree and represent that Cortiam shall at no point be held liable for the actions or omissions of any User that they either interact with, communicate with, or receive any type of services or products from as a result of connecting on Our Website. Cortiam does not provide confidential communications between Users, so please note that any communications between Users is not protected or confidential. You agree to hold Cortiam harmless and indemnify Cortiam from any and all such claims made as a result of Your using Our Website, the Information or entering into an agreement of any kind with a User or anyone else using Our Website.</li>
	</ol>
</li>
<li>Definitions. The following terms are used throughout these Terms of Use and have specific meanings. You should know what each of the terms means.
	<ol style="list-style-type: lower-alpha;">
	<li>The term "Service" or "Services" refers to the services provided by Us, including without limitation access to Cortiam's online community, communication tools, and Information.</li>
	<li>The term "Agreement" refers, collectively, to all the terms, conditions, and notices contained or referenced in these Terms of Use and the Privacy Policy.</li>
	<li>The "Website" refers to Cortiam's Website, all subpages and subdomains, and all Information, Services, and products available at or through the Website.</li>
	<li>The term  "User," "You", "Your" and "Website visitor" refers to the person, company, or organization that has visited or is using Our Website and/or Service and includes registered users and subscribers.</li>
	<li>"Content" refers to content featured or displayed on or through Our Website, including but not limited to text, documents, information, data, articles, opinions, images, photographs, graphics, software, applications, video recordings, audio recordings, sounds, designs, features, and other materials that are made available on the Website either by Us, third parties, or by You. Content includes, without limitation, User-Generated Content, and Third-Party Content which may be submitted by any Cortiam User or others outside of Our Website that are not Users.</li>
	<li>"Information" refers to any Content, software, data, pricing, ratings, products, Services, charts, analysis, comparisons, figures, advertising tips, marketing information, business advice, real estate advice, or graphics made available through this Website.</li>
	<li>The "Cortiam" website, also known as and referred to as www.Cortiam.com, is owned by Cortiam, LLC and is hereafter also referred to as "We", "Us", "Our", "Cortiam" or "Website". When any of these terms are used in the Agreement those terms shall also include Our affiliates, corporate owner, directors, subsidiaries, officers, members, managers, independent contractors, consultants, and employees.</li>
	</ol>
</li>
<li>User Responsibilities. You, and You alone, are responsible for Your account and anything that happens while You are signed in to or using Your account. Your security is Your responsibility.
	<ol style="list-style-type: lower-alpha;">
	<li>User Account Security. If You register as a User, You will create a personalized account which includes a unique username and a password to access Our Website and to receive messages from Cortiam and its Users. You are responsible for maintaining the security of Your account, and You are fully responsible for all activities that occur under the account and any other actions taken in connection with the account. You agree to notify Cortiam immediately of any unauthorized use of Your account, or any other breaches of security. We will not be responsible for any liabilities, losses, or damages arising out of the unauthorized use of Your computer, mobile device, or other computing device and/or account.</li>
	<li>Cortiam does not select or endorse any individual or business User nor any Content they may post anywhere on Our Website. Cortiam does not make any warranty, guarantee, or representation as to the authenticity, ability, competence, quality, finances, or qualifications of any User. Cortiam strongly advises and encourages Users to research, conduct their own due diligence, and do a background check on any User before accepting their advice or services, products, entering into any type of partnership, business, or other relationship, or offering them employment, consulting fees, performance based fees, or equity.</li>
	<li>No Reliance on User-Generated Content. Cortiam Content or User-Generated Content posted on the Website, such as blog posts or forums, is provided for informational and research  purposes only, with no assurance that the Content is true, correct, or accurate. Content on Our Website is not a substitute for professional business, real estate, financial, or legal advice nor is it a solicitation to offer business, financial, real estate, or legal advice regarding specific facts. You should not delay or forego seeking independent advice regarding Your particular situation. Delay in seeking such financial or legal advice could result in waiver of any claims You may have, depending on the applicable statute(s) of limitation. The Content on Our Website, regardless of its source, is not regulated or overseen by any governmental or regulatory authority or agency.</li>
	<li>Cortiam Does Not Guarantee Results. From time to time, Users may submit reviews of other Users; these reviews do not constitute a guarantee, warranty, or prediction regarding the outcome of any future matter. You agree that Cortiam shall have no responsibility or liability of any kind for any of Cortiam's Content or User-Generated Content or business, real estate, or financial advice You encounter on or through the Website, and any use or reliance on Cortiam Content or User-Generated Content or business, real estate, or financial advice is solely at Your own risk. Whether it is User-Generated Content, or Content We post on Our Website, You understand and agree that it is for informational and research purposes only and not to be relied upon and You should seek professional, financial, or legal advice.</li>
	<li>Compliance with Laws. You represent, warrant, and agree that: (i) You have the authority to, and are of legal age in Your jurisdiction to, bind Yourself to this Agreement; (ii) Your use of Our Website will be solely for purposes that are permitted by this Agreement; (iii) Your use of the Service will not infringe or misappropriate the intellectual property rights of any third party; and (iv) Your use of the Service will comply with all local, state and federal laws, rules, and regulations, and with all other Cortiam policies.</li>
	</ol>
</li>
<li>Use and Conduct Restrictions. You are allowed to use Our Website as long as You follow a few basic rules. The following Use Restrictions and Conduct Restrictions are the basic rules We expect Users to follow while using Our Website. We are not responsible for the Content that Our advertisers, marketers or Users post, and We have the right to close accounts if We need to for any reason or no reason.
	<ol style="list-style-type: lower-alpha;">
	<li>Prohibited Content. You agree that You will not under any circumstances transmit any Content (including software, text, images, or other information) that
		<ol style="list-style-type: lower-roman;">
		<li>is unlawful or promotes unlawful activity;</li>
		<li>defames, harasses, abuses, threatens, or incites violence towards any individual or group;</li>
		<li>is pornographic, discriminatory, or otherwise victimizes or intimidates an individual or group on the basis of religion, gender, sexual orientation, race, ethnicity, age, or disability;</li>
		<li>is spam, is machine- or randomly-generated, constitutes unauthorized or unsolicited advertising, chain letters, any other form of unauthorized solicitation, or any form of lottery or gambling;</li>
		<li>contains or installs any viruses, worms, malware, Trojan horses, or other Content that is designed or intended to disrupt, damage, or limit the functioning of any software, hardware, or telecommunications equipment or to damage or obtain unauthorized access to any data or other information of any third party;</li>
		<li>infringes on any proprietary right of any party, including patent, trademark, trade secret, copyright, right of publicity, or other rights;</li>
		<li>impersonates any person or entity, including any of Our employees, representatives, or other Users; or</li>
		<li>violates the privacy of any third party.</li>
		</ol>
	</li>
	<li>Users Must Be Over Age 18. You represent that You are over the age of 18. Cortiam does not target Our Content to children or teenagers under 18. If We learn of any User under the age of 18, We will terminate that User's account immediately.</li>
	<li>No Liability for User Interactions; Cortiam May Monitor Interactions. You agree that any liability, loss, or damage that occurs as a result of any User interactions, including, without limitation, job postings, real estate listings, pitches, partnership requests, service requests and networking requests that You input or receive through Your use of the Service is solely Your responsibility and You indemnify and hold harmless Cortiam from any such claims, demands, lawsuits or losses. At Our discretion, We, or technology We employ, may monitor and/or record Your general interactions with Our Website.</li>
	<li>Right to Terminate Accounts. We have the right (though not the obligation) to, in Our sole discretion, determine whether or not any User conduct is appropriate and complies with these Terms of Use, or terminate or deny access to and use of the Service to any User for any reason, or no reason, with or without prior notice.</li>
	</ol>
</li>
<li>User-Generated Content. You own Your Content, but You allow Us certain rights to it, so that We can display and share the Content You post. We have the right to remove Content in Our sole discretion for any reason or no reason.
	<ol style="list-style-type: lower-alpha;">
	<li>Responsibility for User-Generated Content. You may create Content, written or otherwise, while using the Service ("User-Generated Content"). You are solely responsible for the Content of, and any harm resulting from, any User-Generated Content that You post, upload, link to or otherwise make available via the Service, regardless of the form of that Content. Any liability, loss or damage that occurs as a result of the use of any User-Generated Content that You make available or access through Your use of the Service is solely Your responsibility. We are not responsible for any public display or misuse of Your User-Generated Content and We do not verify, research, or verify the truthfulness or accuracy of any Content on Our Website, which You agree You will separately verify or confirm from outside sources deemed reliable or Your own professional legal, business, or financial advisors without relying on any Content, advertising or marketing that appears on Our Website.</li>
	<li>Right to Post. You represent and warrant that You have the right to post all Content You submit. Specifically, You warrant that You have fully complied with any third party licenses, sublicenses, or permissions relating to such Content and have taken all steps necessary to post, display or pass through such Content on Our Website.</li>
	<li>Cortiam May Modify or Remove Content. We have the right (though not the obligation) to, in Our sole discretion, determine whether or not any User-Generated Content is appropriate and complies with these Terms of Use, or refuse or remove any User-Generated Content that, in Our reasonable opinion, violates any Cortiam policy or is in any way harmful, inappropriate, or objectionable. Cortiam further reserves the right to make formatting and edits and change the manner any User-Generated Content is displayed on Our Website.</li>
	<li>Ownership of User-Generated Content. Except for Content that originates from Us, We do not claim ownership of any Content that is transmitted, stored, or processed in Your account. You retain all ownership of the User-Generated Content You post.</li>
	<li>License Grant. Solely to allow Cortiam to use Content You upload to Our Website reasonably without violating any rights You have in it, You grant Us the following rights: by posting any Content via Our Website, You expressly grant Cortiam and Our successors and assigns a worldwide, sublicensable, fully-paid and royalty-free, and non-exclusive license to use, reproduce, display, modify, adapt, revise, distribute, and perform the Content in connection with Our business purpose without restriction. This license also grants Cortiam the right to sell User-Generated Content or otherwise distribute it outside of Our Website and regardless of the use We make of such Content, Users will not be entitled to any royalties, profits, or revenues of any kind.</li>
	<li>You agree that Our rights to the Content You generate or post, which rights are set forth in this Section and elsewhere in this Agreement, apply even after We or You terminate this Agreement.</li>
	</ol>
</li>
<li>Users. Users include but are not limited to independent persons, businesses, real estate sellers, real estate agents, professionals, entrepreneurs, attorneys, accountants, investors, marketers, advertisers, or service providers who interact with other Users on Our Website. Some Users may be independent contractors or employees of Cortiam .
	<ol style="list-style-type: lower-alpha;">
	<li>No Attorney-Client Relationship through Website Use. Use of the Cortiam Website does not form a principal-agent, attorney-client relationship, or fiduciary relationship among Users. Information posted or made available on or through Our Website, including, without limitation, any responses to questions posted on the Website; the Content; Information posted on the Website; or Information sent in an unsolicited message to a User is not intended as legal, business or financial advice, is not confidential, and does not create a principal-agent, attorney-client relationship, or fiduciary relationship among the Users. It is simply Information to be used for research and informational purposes only and does not replace legal services or advice You would get from retaining an attorney or other professional to handle Your specific legal needs. You agree that any hiring, contracting with, or retaining of real estate agents, service providers, legal counsel, consultants, advisers, financial advisers or others You meet through Our Website will be done outside of Our Website. You agree that communications requiring confidentiality shall take place outside Our Website, such as via telephone, in person, or Your own private email.</li>
	<li>Payment of Users. Certain specific terms govern Users and payment.
		<ol style="list-style-type: lower-roman;">
		<li>Cortiam Is Not A Party To Contracts. Users may contract or enter into agreements with other Users through posting and acceptance of various offers or pitches. Such contracts are solely between the Users. Cortiam will not be a party to any contracts between Users. Cortiam merely facilitates communications between Users by supplying a directory and platform for communication between interested parties. Officers, directors, shareholders, and employees of Cortiam will also be User, but only for administration and monitoring purposes, but even if that is the case, Cortiam is still not a party to contracts between Users.</li>
		<li>All Terms Regarding Fees, Debt or Equity are Strictly between Users. Cortiam does not get involved with the terms or such arrangements for fees, debt, or equity agreed upon between Users and Users agree to indemnify Us and hold Us harmless from any and all such claims, suits, awards, rulings, demands or losses.</li>
		</ol>
	</li>
	</ol>
</li>
<li>Feed Back from Users.  All Users agree to accept and respond to certain emails, questionnaires, and surveys that may be requested from time to time.</li>
<li>Third Party Content. There may be Content from third parties on Our Website, such as articles, blog posts, or forum posts written by other Users or links to other websites. Because We cannot control that Content, We are not responsible for that Content or for the websites that Content may link to.
	<ol style="list-style-type: lower-alpha;">
	<li>Access To Third Party Content. By using Our Website, You will be able to access Content belonging to or originating from third parties ("Third-Party Content"). Your use of Our Website is consent for Cortiam to present this Third-Party Content to You. You acknowledge all responsibility for, and assume all risk for, Your use of Third-Party Content.</li>
	<li>No Responsibility For Third-Party Content. As part of the Service, Cortiam may provide You with convenient links to third-party website(s) as well as other forms of Third-Party Content. We are not responsible for any public display or misuse of Third-Party Content and We do not verify, research, or verify the truthfulness or accuracy of any Third-Party Content, which You agree You will separately verify or confirm from outside sources deemed reliable or Your own professional legal, business, or financial advisors without relying on any Third-Party Content, advertising or marketing that appears on Our Website. We have no control over third-party websites or content or the promotions, materials, information, goods, or services available on them. By linking to such Content, We do not represent or imply that We adopt or endorse, nor are We responsible for, the accuracy or reliability of any opinion, advice, or statement made by parties other than Cortiam. We are not responsible for any Third-Party Content accessed through Our Website. If You decide to leave the Website and access Third-Party Content, You do so at Your own risk and You should be aware that Our terms and policies do not govern Your use of those third-party websites. You should review the applicable terms and policies, including privacy and data gathering practices, of any such Third-Party Content.</li>
	<li>No Authorization To Use Third Party Content. This Agreement does not authorize You to distribute, publicly display, publicly perform, make available, alter, or otherwise use any Third-Party Content except as permitted by those  third-party websites You are visiting.</li>
	</ol>
</li>
<li>Copyright Infringement and DMCA Policy. If You believe that any Content located on Our Website or linked to a third-party website by Us violates Your copyright, please notify Cortiam in accordance with Our Digital Millennium Copyright Act Policy.
	<ol style="list-style-type: lower-alpha;">
	<li>Termination of Repeat Infringer Accounts. Cortiam respects the intellectual property rights of others and requests the same of Users. Pursuant to 17 U.S.C. 512(i) of the United States Copyright Act, We will terminate a User's access to and use of the Website if the User is considered by Us a repeat infringer of the copyrights or other intellectual property rights of Cortiam or others. We may terminate access of Users who We believe repeatedly provide or post protected Third-Party Content without appropriate rights and permissions.</li>
	<li>DMCA Take-Down Notices. If You are a copyright owner or an agent of a copyright owner and believe, in good faith, that any materials provided on Our Website infringe upon Your copyrights, You may submit a notification pursuant to the Digital Millennium Copyright Act (see 17 U.S.C 512) ("DMCA") by sending a properly formatted take-down notice in writing to Cortiam's designated copyright agent: Business: Cortiam Inc., 331 East Main Street, Suite 200- #1175, Rock Hill, SC 29730, Michael Colwell-LaFleur, phone 888-788-7252.</li>
	<li>Response To DMCA Take-Down Notices. If Cortiam takes action in response to an infringement notice, it will make a good faith attempt to contact the party that made such content available by means of the most recent email address, if any, provided by that party to Cortiam. Any DMCA infringement notice may be forwarded to the party that made the content available or to third parties such as <a href="https://lumendatabase.org/" target="_blank">https://lumendatabase.org/</a>.</li>
	<li>Counter-Notices. If You believe that Your User-Generated Content that has been removed from the Website is not infringing, or that You have the authorization from the copyright owner, the copyright owner's agent, or pursuant to the law, to post and use the Content You submitted to the Website, You may send a properly formatted counter-notice to Cortiam's copyright agent using the contact information set forth above.</li>
	<li>Response to DMCA Counter-Notices. If a counter-notice is received by Cortiam's copyright agent, Cortiam may send a copy of the counter-notice to the original complaining party informing such person that it may reinstate the removed content in 10 business days. Unless the copyright owner files an action seeking a court order against the content provider, member or user, the removed content will be reinstated on the Website in 10 to 14 business days after receipt of the counter-notice.</li>
	</ol>
</li>
<li>Intellectual Property Notice. Cortiam retains all ownership of Our intellectual property, including Our copyrights, patents, and trademarks.
	<ol style="list-style-type: lower-alpha;">
	<li>No Transfer. Cortiam retains ownership of all intellectual property rights of any kind related to the Website and Service, including applicable copyrights, patents, trademarks, and other proprietary rights. Other trademarks, service marks, graphics and logos used in connection with the Website and the Service may be the trademarks of other third parties. This Agreement does not transfer from Us to You any Cortiam or third party intellectual property, and all right, title, and interest in and to such property will remain (as between the parties) solely with Us. We reserve all rights that are not expressly granted to You under this Agreement.</li>
	<li>Specifically, Cortiam, and all other trademarks that appear, are displayed, or are used on the Website or as part of the Services are registered or common law trademarks or service marks of Cortiam or are those belonging to others who have given Us approval to use. These trademarks may not be copied, downloaded, reproduced, used, modified, or distributed in any way without prior written permission from Cortiam.</li>
	<li>Any comments or materials sent to Cortiam or posted on the Website, including feedback data, such as questions, comments, suggestions, or the like regarding the content of any such documents (collectively "Feedback"), shall be deemed to be the intellectual property of Cortiam. Cortiam's use of the Feedback will be in compliance with Our Privacy Policy, which is set forth on the Website, and applicable laws. Cortiam shall have no additional obligations with respect to such Feedback and shall be free to reproduce, use, disclose, exhibit, display, transform, create derivative works, and distribute the Feedback to others without limitation. Further, Cortiam shall be free to use any descriptions, testimonials, recommendations, criticism, ideas, concepts, know-how or techniques contained in such Feedback for any purpose whatsoever, including but not limited to improving Our Service, and developing, creating, and marketing products and services incorporating such Feedback.</li>
	</ol>
</li>
<li>Email Communications. We use email and electronic means to stay in touch with Our users.
	<ol style="list-style-type: lower-alpha;">
	<li>Electronic Communications Required. For contractual purposes, You (i) consent to receive communications from Cortiam in an electronic form via the email address You have submitted; and (ii) agree that all Terms of Use, agreements, notices, disclosures, and other communications that Cortiam provides to You electronically satisfy any legal requirement that such communications would satisfy if it were in writing. This section does not affect Your non-waivable rights.</li>
	<li>Legal Notice To Cortiam Must Be In Writing. Communications made through email or the Service's private messaging system will not constitute legal notice to Cortiam or any of Our officers, employees, agents, directors, or representatives in any situation where notice to Cortiam is required by contract or any law or regulation.</li>
	</ol>
</li>
<li>Termination. You may cancel this Agreement and close Your account at any time.
	<ol style="list-style-type: lower-alpha;">
	<li>If You are a new real estate agent to Our Website, for a limited time We are offering a free thirty (30) calendar day sign up period with no credit card required. During that time, You can bid on potential offerings posted by sellers and if You win a bid for a listing You will then be required to provide Your credit card information and pay as a monthly subscriber until You cancel. When We provide You with the seller's information We will debit Your credit card the applicable "Winning Fee" amount. If the seller has not signed Your listing agreement within seven (7) calendar days of You winning the listing, We will refund to You the "Winning Fee" but not the monthly subscription fee. We reserve the right to discontinue the free sign up program at any time.</li>
	<li>You May Terminate This Agreement. If You wish to terminate this Agreement or Your account with Us, You may cancel by sending us notice (or canceling through your dashboard) before the automatic monthly renewal you signed up for, but you will not receive a refund of any portion of the monthly subscription amount. If You wish to delete Your User account data, please email us at info@Cortiam.com. Upon termination be advised that You agree that We retain all rights to Your Content you have provided. We will retain and use Your information as necessary to comply with Our legal obligations, resolve disputes, and enforce Our agreements. Barring legal requirements, We will use our discretion in deciding whether or not to delete Your full profile in approximately thirty days.</li>
	<li>Cortiam May Terminate This Agreement. Cortiam may terminate Your access to all or any part of the Website at any time, with or without cause, with or without notice, effective immediately. Upon termination be advised that You agree that We retain all rights to Your Content you have provided. We will retain and use Your information as necessary to comply with Our legal obligations, resolve disputes, and enforce Our agreements. Barring legal requirements, We will use our discretion in deciding whether or not to delete Your full profile in approximately thirty days.</li>
	<li>Some Provisions Survive Termination. All provisions of this Agreement which by their nature should survive termination will survive termination, including, without limitation, ownership provisions, Our use of the Content, warranty disclaimers, indemnity, and limitations of liability.</li>
	</ol>
</li>
<li>User Dispute Resolution Procedures.
	<ol style="list-style-type: lower-alpha;">
	<li>Users agree that any disputes between Users shall be resolved by arbitration or litigation as set forth in the listing agreement entered into between them. Users agree that any such disputes between Users shall be settled, arbitrated, or litigated between them. Users agree that they shall hold harmless and shall indemnify Cortiam from and against any such claims, demands, lawsuits or losses and that in either event the maximum liability of Cortiam shall be $250.00 in the case of seller disputes against Cortiam and shall be the monthly fees by real estate agent in the case of real estate agent disputes against Cortiam. In the event a User or Users have a dispute of any kind or nature against Cortiam, such User or Users, agree that such claim shall be brought to arbitration with the American Arbitration Association pursuant to their rules of commercial arbitration. Users agree that there shall be a one person arbitration panel. The laws of the State of South Carolina shall apply and the place of arbitration shall be in Fort Mill, South Carolina.</li>
	<li>Jury Trial Waiver. You and Cortiam acknowledge and agree to waive the right to a trial by jury as to all matters, disagreements, disputes, or controversies of any kind or nature that may exist between You and Cortiam.</li>
	<li>No Class Actions or Representative Proceedings. You and Cortiam acknowledge and agree to waive the right to participate as a plaintiff or class member in any purported class action lawsuit, class-wide arbitration, private attorney-general action, or any other representative proceeding as to all disagreements, disputes, or controversies of any kind or nature. Further, unless You and Cortiam both otherwise agree in writing, the arbitrator may not  consolidate more than one party's claims and may not otherwise preside over any form of any class or representative proceeding.</li>
	</ol>
</li>
<li>Disclaimer of Warranties. We provide Our Services as is, and We make no promises or guarantees about Our Services. Please read this section carefully; You should understand what to expect.
	<ol style="list-style-type: lower-alpha;">
	<li>Cortiam provides the Website and the Service "as is," without warranty of any kind. Without limiting the foregoing, Cortiam expressly disclaims all warranties, whether express, implied, or statutory, regarding the Website and the Services including, without limitation, any warranty of merchantability, fitness for a particular purpose, title, security, accuracy and non-infringement.</li>
	<li>Specifically, Cortiam makes no representation or warranty that the Information We provide or that is provided through the Service by Us or others is accurate, reliable, or correct; that the Service will meet Your requirements; that the Service will be available at any particular time or location, that the Service will function in an uninterrupted manner or be secure; that any defects or errors will be corrected; or that the Services are free of viruses or other harmful components. You assume full responsibility and risk of loss resulting from Your use of information, Content or other material obtained from the Service. Some jurisdictions limit or do not permit disclaimers of warranty, so this provision may not apply to You.</li>
	</ol>
</li>
<li>Limitation of Liability. We will not be liable for damages or losses arising from Your use of the Services or arising under this Agreement. Please read this section carefully; it limits Our obligations to You.
	<ol style="list-style-type: lower-alpha;">
	<li>To the extent permitted by applicable law, in no event will Cortiam be liable to You for any loss of profits, use, or data, or for any incidental, indirect, special, consequential or exemplary damages, however arising, that result from (i) the use, disclosure, or display of Information, whether generated, created, or posted by You or others; (ii) Your use or inability to use the Services; (iii) the use of the Website, Services or any of the software or systems that We make available; or (iv) any other interactions with Cortiam or any other User of the Services, whether based on warranty, contract, tort (including negligence) or any other legal theory, and whether or not Cortiam has been informed of the possibility of such damage, and even if a remedy set forth in this Agreement is found to have failed of its essential purpose. Cortiam will have no liability for any failure or delay due to matters beyond Our reasonable control. Some jurisdictions limit or do not permit disclaimers of liability, so this provision may not apply to You.</li>
	<li>The Services may include technical or typographical inaccuracies, mistakes or errors. Cortiam assumes no liability for any errors or omissions in the Content or information contained on Our Website or in the Services and expressly disclaims any responsibility to update this information.</li>
	</ol>
</li>
<li>Third Party Beneficiaries. Users are intended third-party beneficiaries of this section of the Terms of Use. Any legal information provided on Our Website or in the Services is for informational and research purposes only. Cortiam and any creator of Content or Information disclaim, all warranties, either express or implied, statutory, or otherwise, including but not limited to the implied warranties of merchantability, non-infringement of third parties' rights, and fitness for particular purpose, to the fullest extent permitted by law. In no event will Cortiam or User be liable for any damages (including, without limitation, incidental and consequential damages, personal injury / wrongful death, lost profits, or damages resulting from lost data or business interruption) resulting from the use of or inability to use the Services, Website, or the Content, whether based on warranty, contract, tort, or any other legal theory, and whether or not Cortiam or contributors of Content are advised of the possibility of such damages. Neither Cortiam nor contributors of Content are liable for any personal injury, including death, caused by Your use or misuse of the Services, Website, Content, or Information.
</li>
<li>Release and Indemnification.
	<ol style="list-style-type: lower-alpha;">
	</li>You agree to indemnify and hold harmless Cortiam from and against any and all claims and expenses, including attorneys' fees, arising out of Your use of the Services, Website, Information, or Content, including but not limited to Your violation of this Agreement or Our violation of this Agreement.</li>
	</li>If You have a dispute with one or more Users, You release Cortiam from claims, demands and damages (actual and consequential) of every kind and nature, known and unknown, arising out of or in any way connected with such disputes. If You are a California resident, You waive California Civil Code §1542, which says: "A general release does not extend to claims which the creditor does not know or suspect to exist in his favor at the time of executing the release, which if known by him must have materially affected his settlement with the debtor."</li>
	</ol>
</li>
<li>Modification of Terms of Use.  Cortiam may amend this Agreement from time to time, and in Cortiam's sole discretion. If We make changes, We will notify You by revising the date at the top of this Agreement, and in some cases, providing You with additional notice (such as adding a statement to the homepage of Our Service or sending You an email notification). Any changes will be effective immediately upon the posting of the revised Agreement on the Service.  Your continued use of the Website, Services, Information, and Content after the effective date of a revised version of this Agreement constitutes Your acceptance of its terms.
</li>
<li>Miscellaneous. This Agreement is governed by South Carolina law. If We are involved in a merger or are acquired by a person or another entity, We may transfer the rights to this Agreement. You may only agree to these terms if You are able to form a binding contract in Your state or country.  These Terms of Use, the Disclaimer, and Our Privacy Policy are the complete agreement between You and Us, and no other terms apply. This Agreement may only be modified by a written amendment signed by an authorized Cortiam executive, or by the posting by Cortiam of a revised version.
	<ol style="list-style-type: lower-alpha;">
	<li>Governing Law. Except to the extent applicable law provides otherwise, this Agreement between You and Cortiam and any access to or use of the Website, Information, Content, or the Services are governed by the laws of the State of South Carolina, without regard to conflict of law provisions.</li>
	<li>Severability. If any part of this Agreement is held invalid or unenforceable, that portion of the Agreement will be construed to reflect the parties' original intent. The remaining portions will remain in full force and effect. Any failure on the part of Cortiam to enforce any provision of this Agreement will not be considered a waiver of Our right to enforce such provision. Our rights under this Agreement will survive any termination of this Agreement.</li>
	<li>Limitation of Term of Action. You agree that any cause of action related to or arising out of Your relationship with Cortiam must commence, by filing an arbitration claim pursuant to the terms of this Agreement, not later than three hundred and sixty-five (365) calendar days after the claim or cause of action accrues. Otherwise, such claim or cause of action and Your rights to bring such action shall be permanently barred.</li>
	<li>Non-Assignability. Cortiam may assign or delegate the terms of this Agreement, in whole or in part, to any person or entity at any time with or without Your consent. You may not assign or delegate any rights or obligations under the Terms of Use or Privacy Policy without Cortiam's prior written consent, and any unauthorized assignment and delegation by You is void.</li>
	<li>Section Headings and Summaries Non-Binding. Throughout this Agreement, each section includes titles and brief summaries of the following terms and conditions. These section titles and brief summaries are not legally binding.</li>
	<li>Authorization to Contract. You represent and warrant that if You are an individual, You are of legal age to form a binding contract; or that if You are registering on behalf of an entity, that You are authorized to enter into, and bind the entity to this Agreement.</li>
	</ol>
</li>
</ol>
<p>You acknowledge that You have read this Agreement, understand its terms and conditions, and will be bound by this Agreement in its entirety. Your only option should You not agree is to cease using this Website and the Services.</p>

		  	</div>
		  </div>
  	</div>
	</div>
	<div class="orange-bar">
	  <div class="container">
			<div class="row">
			  <div class="col-sm-12 text-center">
			  	<h3>READY TO GET STARTED?</h3>
			  	<h4 class="px-5 mb-4">Selling your home on your terms is one click away. </h4>
			  	<a href="<?php echo base_url('sign-up');?>" class="button-white">GET STARTED</a>
			  </div>
		  </div>
	  </div>
  </div>
</main>